# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9055aef69ac34bdb4997a81f2a2aaf0eff3af66f4fa6032374567dbed2405048bbb8d0503dbee79315a0d3fa784498d19696618d6cd66a25fbf9615f03faf6ea

test:
  secret_key_base: 5247c2d566821466b8882345eb1bff28adc80a7a0d5af4579a72fb6c9ae95be94767cdc2595165166920130b18186e542e9ea3c273f2720a11b2ff3f224368e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
